.nh
.TH "PC" "1" "Dec 2025" "Pinecone CLI" "Pinecone CLI Manual"

.SH NAME
.PP
pc-auth-local-keys-prune - Delete project API keys that the CLI is managing in local storage


.SH SYNOPSIS
.PP
\fBpc auth local-keys prune [flags]\fP


.SH DESCRIPTION
.PP
Delete project API keys that the CLI is managing in local state.

.PP
This operation removes managed keys from local storage and deletes them
from Pinecone servers. Any integrations that authenticate with these
keys outside of the CLI will immediately stop working.

.PP
By default, this command deletes all API keys that the CLI is managing, whether
they were created by the CLI or the user. You can filter the operation by
project ID or key origin. Options for origin are: 'cli', 'user', or 'all' (default).

.PP
See: https://docs.pinecone.io/reference/cli/authentication


.SH OPTIONS
.PP
\fB--dry-run\fP[=false]
	Preview keys that will be deleted without applying changes

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for prune

.PP
\fB--id\fP=""
	Only prune keys for a specific project

.PP
\fB-j\fP, \fB--json\fP[=false]
	Output as JSON

.PP
\fB-o\fP, \fB--origin\fP="all"
	Filter deletions by key origin: 'cli', 'user', 'all'

.PP
\fB--skip-confirmation\fP[=false]
	Skip confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress output

.PP
\fB--timeout\fP=1m0s
	timeout for commands, defaults to 60s (0 to disable)


.SH EXAMPLE
.EX
  # Prune all locally managed keys that the CLI has created
  $ pc auth local-keys prune --origin cli --skip-confirmation

  # Prune all locally managed keys that the user has created and stored
  $ pc auth local-keys prune --origin user --skip-confirmation

  # Show a dry run plan of pruning all keys (origin defaults to "all")
  # and then apply the changes
  $ pc auth local-keys prune --dry-run --skip-confirmation
  $ pc auth local-keys prune --skip-confirmation

.EE


.SH SEE ALSO
.PP
\fBpc-auth-local-keys(1)\fP


.SH HISTORY
.PP
19-Dec-2025 Auto generated by spf13/cobra
