.nh
.TH "PC" "1" "Dec 2025" "Pinecone CLI" "Pinecone CLI Manual"

.SH NAME
.PP
pc-auth-configure - Configure authentication credentials for the Pinecone CLI


.SH SYNOPSIS
.PP
\fBpc auth configure [flags]\fP


.SH DESCRIPTION
.PP
Configure the CLI to use a service account or API key for authentication.

.PP
When you configure a service account, the CLI automatically targets the organization
associated with that account, and prompts you to select a project if multiple exist.

.PP
An API overrides any explicitly targeted organization and project, instead targeting
the organization and project associated with the API key itself. API keys do not grant
Admin API access.

.PP
See: https://docs.pinecone.io/reference/cli/authentication


.SH OPTIONS
.PP
\fB--api-key\fP=""
	Default API key override for the Pinecone CLI

.PP
\fB--client-id\fP=""
	Service account client ID for the Pinecone CLI

.PP
\fB--client-secret\fP=""
	Service account client secret for the Pinecone CLI

.PP
\fB--client-secret-stdin\fP[=false]
	Read the client secret from stdin

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for configure

.PP
\fB-j\fP, \fB--json\fP[=false]
	output as JSON

.PP
\fB-p\fP, \fB--project-id\fP=""
	The ID of the project to target after authenticating with service account credentials

.PP
\fB--prompt-if-missing\fP[=false]
	Prompt for missing credentials if not provided


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress output

.PP
\fB--timeout\fP=1m0s
	timeout for commands, defaults to 60s (0 to disable)


.SH EXAMPLE
.EX
  # Configure service account credentials
  $ pc auth configure --client-id "client-id" --client-secret "client-secret"

  # Configure default API key
  $ pc auth configure --api-key "api-key"

.EE


.SH SEE ALSO
.PP
\fBpc-auth(1)\fP


.SH HISTORY
.PP
19-Dec-2025 Auto generated by spf13/cobra
