.nh
.TH "PC" "1" "Dec 2025" "Pinecone CLI" "Pinecone CLI Manual"

.SH NAME
.PP
pc-index-vector-upsert - Upsert vectors into an index from a JSON/JSONL file


.SH SYNOPSIS
.PP
\fBpc index vector upsert [flags]\fP


.SH DESCRIPTION
.PP
Upsert vectors into an index namespace from a JSON or JSONL payload.

.PP
The request --file may be a JSON object containing "vectors": [...] or a JSONL stream of Vector objects.
Control batch size with --batch-size. Bodies can be inline JSON, loaded from ./file.json[l], or read from stdin with '-'.

.PP
Body schema: UpsertBody (vectors shaped like pinecone.Vector: https://pkg.go.dev/github.com/pinecone-io/go-pinecone/v5/pinecone#Vector)


.SH OPTIONS
.PP
\fB-b\fP, \fB--batch-size\fP=500
	size of batches to upsert (default: 500)

.PP
\fB--body\fP=""
	alias for --file

.PP
\fB--file\fP=""
	request body JSON or JSONL (inline, ./path.json[l], or '-' for stdin; only one argument may use stdin)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for upsert

.PP
\fB-n\fP, \fB--index-name\fP=""
	name of index to upsert into

.PP
\fB-j\fP, \fB--json\fP[=false]
	output as JSON

.PP
\fB--namespace\fP="\fBdefault\fP"
	namespace to upsert into


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress output

.PP
\fB--timeout\fP=1m0s
	timeout for commands, defaults to 60s (0 to disable)


.SH EXAMPLE
.EX
  $ pc index vector upsert --index-name my-index --namespace my-namespace --body ./vectors.json
  $ pc index vector upsert --index-name my-index --namespace my-namespace --body ./vectors.jsonl
  $ cat payload.json | pc index vector upsert --index-name my-index --namespace my-namespace --body -

.EE


.SH SEE ALSO
.PP
\fBpc-index-vector(1)\fP


.SH HISTORY
.PP
19-Dec-2025 Auto generated by spf13/cobra
