.nh
.TH "PC" "1" "Dec 2025" "Pinecone CLI" "Pinecone CLI Manual"

.SH NAME
.PP
pc-index-vector-query - Query an index by vector values


.SH SYNOPSIS
.PP
\fBpc index vector query [flags]\fP


.SH DESCRIPTION
.PP
Query vectors in an index by dense or sparse vector values, or by vector ID.

.PP
Use --top-k to control result count and --include-values/--include-metadata to enrich results.
An optional metadata filter can be used to filter the results.

.PP
JSON inputs may be inline, loaded from ./file.json[l], or read from stdin with '-'.

.PP
When providing sparse values, both --sparse-indices and --sparse-values must be present.
A --body payload can pass id, vector, sparse_values, filter, top_k, include_values, and include_metadata.


.SH OPTIONS
.PP
\fB--body\fP=""
	request body JSON (inline, ./path.json, or '-' for stdin; only one argument may use stdin)

.PP
\fB-f\fP, \fB--filter\fP=
	metadata filter to apply to the query (inline JSON, ./path.json, or '-' for stdin)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for query

.PP
\fB-i\fP, \fB--id\fP=""
	ID of the vector to query against

.PP
\fB--include-metadata\fP[=false]
	include metadata in the query results

.PP
\fB--include-values\fP[=false]
	include vector values in the query results

.PP
\fB-n\fP, \fB--index-name\fP=""
	name of the index to query

.PP
\fB-j\fP, \fB--json\fP[=false]
	output as JSON

.PP
\fB--namespace\fP="\fBdefault\fP"
	index namespace to query

.PP
\fB--sparse-indices\fP=
	sparse indices to query against (inline JSON array, ./path.json, or '-' for stdin)

.PP
\fB--sparse-values\fP=
	sparse values to query against (inline JSON array, ./path.json, or '-' for stdin)

.PP
\fB-k\fP, \fB--top-k\fP=10
	maximum number of results to return

.PP
\fB-v\fP, \fB--vector\fP=
	vector values to query against (inline JSON array, ./path.json, or '-' for stdin)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress output

.PP
\fB--timeout\fP=1m0s
	timeout for commands, defaults to 60s (0 to disable)


.SH EXAMPLE
.EX
  $ pc index vector query --index-name my-index --id doc-123 --top-k 10 --include-metadata

  $ pc index vector query --index-name my-index --vector '[0.1, 0.2, 0.3]' --top-k 25
  $ pc index vector query --index-name my-index --vector ./vector.json --top-k 25 --include-metadata
  $ jq -c '.embedding' doc.json | pc index vector query --index-name my-index --vector - --top-k 20

  $ pc index vector query --index-name my-index --sparse-indices ./indices.json --sparse-values ./values.json --top-k 15

  $ pc index vector query --index-name my-index --vector ./vector.json --filter '{"genre":{"$eq":"sci-fi"}}' --include-metadata

  $ pc index vector query --index-name my-index --body ./query.json
  $ cat query.json | pc index vector query --index-name my-index --body -

.EE


.SH SEE ALSO
.PP
\fBpc-index-vector(1)\fP


.SH HISTORY
.PP
19-Dec-2025 Auto generated by spf13/cobra
