.nh
.TH "PC" "1" "Dec 2025" "Pinecone CLI" "Pinecone CLI Manual"

.SH NAME
.PP
pc-target - Set the target organization and project context for the CLI


.SH SYNOPSIS
.PP
\fBpc target [flags]\fP


.SH DESCRIPTION
.PP
Set the target organization and project context for the CLI.

.PP
Operations for resources within the control and data plane take place in the context of a specific project.
After authenticating through the CLI with user login or service account credentials, you can use
this command to set the target organization or project context for control and data plane operations.

.PP
When using a default API key for authentication, there's no need to specify a project context, because the API
key is already associated with a specific organization and project.


.SH OPTIONS
.PP
\fB--clear\fP[=false]
	Clear the target context

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for target

.PP
\fB-j\fP, \fB--json\fP[=false]
	output as JSON

.PP
\fB-o\fP, \fB--org\fP=""
	Organization name

.PP
\fB--organization-id\fP=""
	Organization ID

.PP
\fB-p\fP, \fB--project\fP=""
	Project name

.PP
\fB--project-id\fP=""
	Project ID

.PP
\fB-s\fP, \fB--show\fP[=false]
	Show the current context


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress output

.PP
\fB--timeout\fP=1m0s
	timeout for commands, defaults to 60s (0 to disable)


.SH EXAMPLE
.EX
  # Interactively target from available organizations and projects
  $ pc target

  # Target an organization and project by name
  $ pc target --org "organization-name" -project "project-name"

  # Target a project by name
  $ pc target --project "project-name"

  # Target an organization and project by ID
  $ pc target --organization-id "org-id" --project-id "project-id"

.EE


.SH SEE ALSO
.PP
\fBpc(1)\fP


.SH HISTORY
.PP
19-Dec-2025 Auto generated by spf13/cobra
