.nh
.TH "PC" "1" "Dec 2025" "Pinecone CLI" "Pinecone CLI Manual"

.SH NAME
.PP
pc - Manage your Pinecone vector database infrastructure from the command line


.SH SYNOPSIS
.PP
\fBpc [flags]\fP


.SH DESCRIPTION
.PP
The Pinecone CLI (pc) provides a complete interface for managing your
vector database infrastructure, from authentication and project setup to
creating indexes and managing API keys.

.PP
GETTING STARTED

.RS
.IP "  1." 5
Authenticate
$ pc login
Opens a browser to log in with your Pinecone account
.IP "  2." 5
Set a target context (organization + project)
$ pc target --org "My organization" --project "My project"
This determines where indexes and resources will be created
.IP "  3." 5
Create an index
$ pc index create --name "My index" --dimension 1536 --metric "cosine" \\
 --cloud "aws" --region "us-west-2"

.RE

.PP
See: https://docs.pinecone.io/reference/cli/overview


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for pc

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	suppress output

.PP
\fB--timeout\fP=1m0s
	timeout for commands, defaults to 60s (0 to disable)


.SH EXAMPLE
.EX
  $ pc login
  $ pc target
  $ pc index create --help

.EE


.SH SEE ALSO
.PP
\fBpc-api-key(1)\fP, \fBpc-auth(1)\fP, \fBpc-backup(1)\fP, \fBpc-collection(1)\fP, \fBpc-config(1)\fP, \fBpc-index(1)\fP, \fBpc-login(1)\fP, \fBpc-logout(1)\fP, \fBpc-organization(1)\fP, \fBpc-project(1)\fP, \fBpc-target(1)\fP, \fBpc-version(1)\fP, \fBpc-whoami(1)\fP


.SH HISTORY
.PP
19-Dec-2025 Auto generated by spf13/cobra
